services:
  mysql:
    container_name: console-app-mysql-1
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: console-app
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_mysql:/var/lib/mysql
    networks:
      - mysql_network
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - mysql_network

volumes:
  db_mysql:

networks:
  mysql_network:
